using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace OcuHubBackend.Migrations
{
    /// <inheritdoc />
    public partial class FixUserRelations : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_UserProfileCustoms_Users_UserId1",
                table: "UserProfileCustoms");

            migrationBuilder.DropForeignKey(
                name: "FK_UserProfileGenerateds_Users_UserId1",
                table: "UserProfileGenerateds");

            migrationBuilder.DropPrimaryKey(
                name: "PK_UserProfileGenerateds",
                table: "UserProfileGenerateds");

            migrationBuilder.DropIndex(
                name: "IX_UserProfileGenerateds_UserId1",
                table: "UserProfileGenerateds");

            migrationBuilder.DropPrimaryKey(
                name: "PK_UserProfileCustoms",
                table: "UserProfileCustoms");

            migrationBuilder.DropIndex(
                name: "IX_UserProfileCustoms_UserId1",
                table: "UserProfileCustoms");

            migrationBuilder.DropPrimaryKey(
                name: "PK_UserAppSettings",
                table: "UserAppSettings");

            migrationBuilder.RenameColumn(
                name: "UserId1",
                table: "UserProfileGenerateds",
                newName: "Id");

            migrationBuilder.RenameColumn(
                name: "InferredSubspecialties",
                table: "UserProfileGenerateds",
                newName: "SuggestedCountry");

            migrationBuilder.RenameColumn(
                name: "InferredPlaces",
                table: "UserProfileGenerateds",
                newName: "SuggestedCity");

            migrationBuilder.RenameColumn(
                name: "GeneratedAt",
                table: "UserProfileGenerateds",
                newName: "UpdatedAt");

            migrationBuilder.RenameColumn(
                name: "UserId1",
                table: "UserProfileCustoms",
                newName: "Id");

            migrationBuilder.RenameColumn(
                name: "Subspecialties",
                table: "UserProfileCustoms",
                newName: "Workplace");

            migrationBuilder.RenameColumn(
                name: "Places",
                table: "UserProfileCustoms",
                newName: "PhoneNumber");

            migrationBuilder.RenameColumn(
                name: "Degrees",
                table: "UserProfileCustoms",
                newName: "Notes");

            migrationBuilder.AddColumn<DateTime>(
                name: "CreatedAt",
                table: "UserProfileGenerateds",
                type: "timestamp with time zone",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                table: "UserProfileGenerateds",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "ProfessionTitle",
                table: "UserProfileGenerateds",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "City",
                table: "UserProfileCustoms",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Country",
                table: "UserProfileCustoms",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "CreatedAt",
                table: "UserProfileCustoms",
                type: "timestamp with time zone",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            migrationBuilder.AddColumn<DateTime>(
                name: "UpdatedAt",
                table: "UserProfileCustoms",
                type: "timestamp with time zone",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            migrationBuilder.AlterColumn<string>(
                name: "UserId",
                table: "UserAppSettings",
                type: "text",
                nullable: false,
                oldClrType: typeof(Guid),
                oldType: "uuid");

            migrationBuilder.AddColumn<int>(
                name: "Id",
                table: "UserAppSettings",
                type: "integer",
                nullable: false,
                defaultValue: 0)
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            migrationBuilder.AddPrimaryKey(
                name: "PK_UserProfileGenerateds",
                table: "UserProfileGenerateds",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_UserProfileCustoms",
                table: "UserProfileCustoms",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_UserAppSettings",
                table: "UserAppSettings",
                column: "Id");

            migrationBuilder.CreateIndex(
                name: "IX_UserProfileGenerateds_UserId",
                table: "UserProfileGenerateds",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_UserProfileCustoms_UserId",
                table: "UserProfileCustoms",
                column: "UserId");

            migrationBuilder.AddForeignKey(
                name: "FK_UserProfileCustoms_Users_UserId",
                table: "UserProfileCustoms",
                column: "UserId",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_UserProfileGenerateds_Users_UserId",
                table: "UserProfileGenerateds",
                column: "UserId",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_UserProfileCustoms_Users_UserId",
                table: "UserProfileCustoms");

            migrationBuilder.DropForeignKey(
                name: "FK_UserProfileGenerateds_Users_UserId",
                table: "UserProfileGenerateds");

            migrationBuilder.DropPrimaryKey(
                name: "PK_UserProfileGenerateds",
                table: "UserProfileGenerateds");

            migrationBuilder.DropIndex(
                name: "IX_UserProfileGenerateds_UserId",
                table: "UserProfileGenerateds");

            migrationBuilder.DropPrimaryKey(
                name: "PK_UserProfileCustoms",
                table: "UserProfileCustoms");

            migrationBuilder.DropIndex(
                name: "IX_UserProfileCustoms_UserId",
                table: "UserProfileCustoms");

            migrationBuilder.DropPrimaryKey(
                name: "PK_UserAppSettings",
                table: "UserAppSettings");

            migrationBuilder.DropColumn(
                name: "CreatedAt",
                table: "UserProfileGenerateds");

            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                table: "UserProfileGenerateds");

            migrationBuilder.DropColumn(
                name: "ProfessionTitle",
                table: "UserProfileGenerateds");

            migrationBuilder.DropColumn(
                name: "City",
                table: "UserProfileCustoms");

            migrationBuilder.DropColumn(
                name: "Country",
                table: "UserProfileCustoms");

            migrationBuilder.DropColumn(
                name: "CreatedAt",
                table: "UserProfileCustoms");

            migrationBuilder.DropColumn(
                name: "UpdatedAt",
                table: "UserProfileCustoms");

            migrationBuilder.DropColumn(
                name: "Id",
                table: "UserAppSettings");

            migrationBuilder.RenameColumn(
                name: "UpdatedAt",
                table: "UserProfileGenerateds",
                newName: "GeneratedAt");

            migrationBuilder.RenameColumn(
                name: "SuggestedCountry",
                table: "UserProfileGenerateds",
                newName: "InferredSubspecialties");

            migrationBuilder.RenameColumn(
                name: "SuggestedCity",
                table: "UserProfileGenerateds",
                newName: "InferredPlaces");

            migrationBuilder.RenameColumn(
                name: "Id",
                table: "UserProfileGenerateds",
                newName: "UserId1");

            migrationBuilder.RenameColumn(
                name: "Workplace",
                table: "UserProfileCustoms",
                newName: "Subspecialties");

            migrationBuilder.RenameColumn(
                name: "PhoneNumber",
                table: "UserProfileCustoms",
                newName: "Places");

            migrationBuilder.RenameColumn(
                name: "Notes",
                table: "UserProfileCustoms",
                newName: "Degrees");

            migrationBuilder.RenameColumn(
                name: "Id",
                table: "UserProfileCustoms",
                newName: "UserId1");

            migrationBuilder.AlterColumn<Guid>(
                name: "UserId",
                table: "UserAppSettings",
                type: "uuid",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AddPrimaryKey(
                name: "PK_UserProfileGenerateds",
                table: "UserProfileGenerateds",
                column: "UserId");

            migrationBuilder.AddPrimaryKey(
                name: "PK_UserProfileCustoms",
                table: "UserProfileCustoms",
                column: "UserId");

            migrationBuilder.AddPrimaryKey(
                name: "PK_UserAppSettings",
                table: "UserAppSettings",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_UserProfileGenerateds_UserId1",
                table: "UserProfileGenerateds",
                column: "UserId1");

            migrationBuilder.CreateIndex(
                name: "IX_UserProfileCustoms_UserId1",
                table: "UserProfileCustoms",
                column: "UserId1");

            migrationBuilder.AddForeignKey(
                name: "FK_UserProfileCustoms_Users_UserId1",
                table: "UserProfileCustoms",
                column: "UserId1",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_UserProfileGenerateds_Users_UserId1",
                table: "UserProfileGenerateds",
                column: "UserId1",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
