using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OcuHubBackend.Data;
using OcuHubBackend.Models;

namespace OcuHubBackend.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class UserProfileGeneratedController : ControllerBase
    {
        private readonly OcuHubDbContext _context;

        public UserProfileGeneratedController(OcuHubDbContext context)
        {
            _context = context;
        }

        [HttpGet("{firebaseUid}")]
        public async Task<ActionResult<UserProfileGenerated>> GetProfile(string firebaseUid)
        {
            var profile = await _context.UserProfileGenerateds
                .FirstOrDefaultAsync(p => p.UserId == firebaseUid);

            if (profile == null)
                return NotFound();

            return Ok(profile);
        }

        [HttpPost]
        public async Task<ActionResult<UserProfileGenerated>> CreateOrUpdateProfile(UserProfileGenerated model)
        {
            var existing = await _context.UserProfileGenerateds
                .FirstOrDefaultAsync(p => p.UserId == model.UserId);

            if (existing != null)
            {
                existing.ProfessionTitle = model.ProfessionTitle;
                existing.SuggestedCountry = model.SuggestedCountry;
                existing.SuggestedCity = model.SuggestedCity;
                existing.IsAutoGenerated = model.IsAutoGenerated;
                existing.UpdatedAt = DateTime.UtcNow;
            }
            else
            {
                model.CreatedAt = DateTime.UtcNow;
                model.UpdatedAt = DateTime.UtcNow;
                _context.UserProfileGenerateds.Add(model);
            }

            await _context.SaveChangesAsync();
            return Ok(model);
        }
    }
}