// Path: Controllers/UserProfileGeneratedController.cs

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OcuHubBackend.Data;
using OcuHubBackend.Models;

namespace OcuHubBackend.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class UserProfileGeneratedController : ControllerBase
    {
        private readonly OcuHubDbContext _context;

        public UserProfileGeneratedController(OcuHubDbContext context)
        {
            _context = context;
        }

        [HttpGet("{firebaseUid}")]
        public async Task<ActionResult<UserProfileGenerated>> GetUserProfileGenerated(string firebaseUid)
        {
            var profile = await _context.UserProfileGenerateds
                .FirstOrDefaultAsync(p => p.UserId == firebaseUid);

            if (profile == null)
                return NotFound();

            return Ok(profile);
        }

        [HttpPost("sync")]
        public async Task<IActionResult> SyncUserProfileGenerated(UserProfileGenerated userProfileGenerated)
        {
            var existing = await _context.UserProfileGenerateds
                .FirstOrDefaultAsync(p => p.UserId == userProfileGenerated.UserId);

            if (existing != null)
            {
                existing.ProfessionTitle = userProfileGenerated.ProfessionTitle;
                existing.SuggestedCountry = userProfileGenerated.SuggestedCountry;
                existing.SuggestedCity = userProfileGenerated.SuggestedCity;
                existing.UpdatedAt = DateTime.UtcNow;
                existing.IsAutoGenerated = userProfileGenerated.IsAutoGenerated;
            }
            else
            {
                userProfileGenerated.CreatedAt = DateTime.UtcNow;
                userProfileGenerated.UpdatedAt = DateTime.UtcNow;
                _context.UserProfileGenerateds.Add(userProfileGenerated);
            }

            await _context.SaveChangesAsync();
            return Ok();
        }
    }
}