using System.ComponentModel.DataAnnotations;

namespace OcuHubBackend.Models;

public class UserProfileGenerated
{
    [Key]
    public Guid UserId { get; set; }

    public string FirebaseUid { get; set; } = null!;
    public string? ProfessionTitle { get; set; }
    public string? SuggestedCountry { get; set; }
    public string? SuggestedCity { get; set; }
    public bool IsAutoGenerated { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
}