using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OcuHubBackend.Models
{
    public class UserProfileGenerated
    {
        [Key]
        public Guid Id { get; set; }

        [Required]
        public Guid UserId { get; set; }

        [ForeignKey("UserId")]
        public User? User { get; set; }

        public string? ProfessionTitle { get; set; }

        public string? SuggestedCountry { get; set; }

        public string? SuggestedCity { get; set; }

        public bool IsAutoGenerated { get; set; } = true;

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
    }
}